name: Deploy to EC2

on:
  push:
    branches:
      - cicd-setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t finance-app .

      - name: Save Docker image
        run: docker save finance-app > image.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "image.tar"
          target: "/home/ubuntu/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop finance-app || true
            docker rm finance-app || true
            docker load < image.tar
            docker run -d -p 8501:8501 --name finance-app finance-app
